-- DB03
-- p25 ~ 27p
SELECT * FROM T_STUDENT ;

--1번
SELECT STUDNO ,name , ID, GRADE , JUMIN , BIRTHDAY , TEL ,
HEIGHT, WEIGHT , DEPTNO1 , DEPTNO2 , PROFNO 
FROM T_STUDENT WHERE HEIGHT >= 180;

--2번
SELECT name, weight FROM T_STUDENT 
WHERE WEIGHT BETWEEN 60 AND 80
ORDER BY WEIGHT ASC ;

--3번
SELECT NAME, DEPTNO1 FROM T_STUDENT 
WHERE DEPTNO1 IN (101,201)
ORDER BY DEPTNO1 ASC;

--4번
SELECT NAME FROM T_STUDENT WHERE NAME LIKE '김%'; 

--5번
SELECT NAME, GRADE , HEIGHT FROM T_STUDENT 
WHERE GRADE = 4 AND HEIGHT > 170;

--6번
SELECT NAME , HEIGHT , GRADE ,WEIGHT FROM T_STUDENT 
WHERE GRADE = 1 OR WEIGHT >=80;

--7번
SELECT NAME , GRADE , HEIGHT , WEIGHT FROM T_STUDENT
WHERE GRADE = 2 AND HEIGHT > 180 AND WEIGHT > 70;

--8번
SELECT NAME , GRADE , HEIGHT, WEIGHT FROM T_STUDENT 
WHERE GRADE =2 AND (HEIGHT > 180 OR WEIGHT > 70);

--9번

SELECT  , FROM T_EMP 



--10번
SELECT NAME , BIRTHDAY , HEIGHT , WEIGHT 
FROM T_STUDENT WHERE GRADE = 1
ORDER BY BIRTHDAY ASC ;