-- 산술 연산자 

SELECT ename, sal, sal * 1.1 --급여 10% 인상
FROM T_EMP ;

SELECT ENAME , SAL , COMM 
FROM T_EMP ;

SELECT SAL , COMM , SAL + COMM -- null 값과의 산술연산은 무조건 null
FROM T_EMP ;

-- WHERE 조건절
SELECT * FROM  T_EMP WHERE job = 'SALESMAN' -- 대소문자구분;

SELECT ENAME , SAL , DEPTNO 
FROM T_EMP 
WHERE deptno = 10;

SELECT ENAME , SAL 
FROM T_EMP 
WHERE sal > 2000;

SELECT ENAME , EMPNO , SAL 
FROM T_EMP 
WHERE ENAME  = 'SCOTT';

SELECT ename, sal FROM t_emp
          WHERE sal BETWEEN 2000 AND 3000;

         
SELECT * FROM T_STUDENT ;

SELECT NAME , GRADE FROM T_STUDENT WHERE GRADE = 2 or GRADE = 3;
SELECT NAME , GRADE FROM T_STUDENT WHERE GRADE IN (2,3);
SELECT NAME , GRADE FROM T_STUDENT WHERE GRADE > 1 AND GRADE < 4;
SELECT NAME , GRADE FROM T_STUDENT WHERE GRADE BETWEEN 2 AND 3;
         
SELECT * FROM T_PROFESSOR ;
SELECT NAME , PAY , "POSITION" 
FROM T_PROFESSOR WHERE PAY > 300 AND "POSITION" = '정교수';

SELECT NAME , "POSITION" 
FROM T_PROFESSOR WHERE BONUS IS NULL; 

SELECT NAME 
FROM T_PROFESSOR WHERE name LIKE '김%';

SELECT ENAME 
FROM T_EMP WHERE ENAME LIKE '%NE%';

SELECT ENAME 
FROM T_EMP WHERE ENAME LIKE '_A%';

-- ORDER BY
SELECT ename FROM T_EMP WHERE ENAME LIKE '%L%'
ORDER BY ENAME DESC;

SELECT ename, job, sal FROM T_EMP 
ORDER BY job DESC, sal ASC ;

SELECT name, grade, height FROM T_STUDENT 
ORDER BY GRADE ASC , HEIGHT DESC ;


         