
--#7101
SELECT *FROM T_EMP ;
--SCOTT 인 직원의 급여 추출
SELECT sal FROM t_emp WHERE ENAME = 'SCOTT';
SELECT ENAME , SAL 
FROM T_EMP 
WHERE sal > (SELECT sal FROM t_emp WHERE ENAME = 'SCOTT');

--#7102
SELECT MAX(height) FROM T_STUDENT ;
SELECT name, HEIGHT 
FROM T_STUDENT 
WHERE HEIGHT = (SELECT MAX(height) FROM T_STUDENT);

--========================단일행===============================

--#7103
SELECT * FROM T_STUDENT ;
SELECT * FROM T_DEPARTMENT ;

SELECT DEPTNO1 
FROM T_STUDENT WHERE NAME = '이윤나';

SELECT s.NAME 학생이름, d.DNAME "1전공"
FROM T_STUDENT s, T_DEPARTMENT d
WHERE s.DEPTNO1 = d.DEPTNO AND s.DEPTNO1 = 
	(SELECT DEPTNO1 FROM T_STUDENT WHERE NAME = '이윤나');

--#7104
SELECT * FROM T_DEPARTMENT ;
SELECT * FROM T_PROFESSOR ;
SELECT HIREDATE FROM T_PROFESSOR WHERE NAME = '송도권';

SELECT p.NAME 교수명, TO_CHAR(p.HIREDATE, 'YYYY-MM-DD') 입사일, d.DNAME 학과명
FROM T_PROFESSOR p, T_DEPARTMENT d
WHERE p.DEPTNO = d.DEPTNO AND p.HIREDATE > (SELECT HIREDATE FROM T_PROFESSOR WHERE NAME = '송도권');

--#7105
SELECT * FROM T_STUDENT ;
SELECT AVG(WEIGHT) FROM T_STUDENT WHERE DEPTNO1 = 101;

SELECT NAME 이름 , WEIGHT 몸무게 
FROM T_STUDENT 
WHERE WEIGHT > (SELECT AVG(WEIGHT) FROM T_STUDENT WHERE DEPTNO1 = 101);

--#7106
SELECT * FROM T_PROFESSOR ;
SELECT HIREDATE FROM T_PROFESSOR WHERE NAME = '심슨';
SELECT NAME FROM T_PROFESSOR WHERE HIREDATE = (SELECT HIREDATE FROM T_PROFESSOR WHERE NAME = '심슨');
SELECT PAY FROM T_PROFESSOR WHERE NAME = '조인형';

SELECT NAME 이름, PAY 급여, TO_CHAR(HIREDATE, 'YYYY-MM-DD') 입사일
FROM T_PROFESSOR 
WHERE PAY < (SELECT PAY FROM T_PROFESSOR WHERE NAME = '조인형')
	AND HIREDATE = (SELECT HIREDATE FROM T_PROFESSOR WHERE NAME = '심슨');

--====================다중행================================================
--#7107
SELECT * FROM T_EMP2; --DEPTNO 
SELECT * FROM T_DEPT2; --DCODE
--서울지사 부서들 DCODE
SELECT DCODE FROM T_DEPT2 WHERE AREA = '서울지사';
SELECT EMPNO , NAME , DEPTNO 
FROM T_EMP2 
WHERE DEPTNO IN (SELECT DCODE FROM T_DEPT2 WHERE AREA = '서울지사');

--#7108
SELECT * FROM T_EMP2;
--과장직급의 연봉
SELECT PAY FROM T_EMP2 WHERE POST = '과장';
SELECT NAME 이름, POST 직급, TO_CHAR(PAY, '999,999,999') || '원' "연봉"
FROM T_EMP2 
WHERE PAY >ANY (SELECT PAY FROM T_EMP2 WHERE POST = '과장');

--#7109
SELECT * FROM T_STUDENT ;
--4학년 학생들의 몸무게 
SELECT WEIGHT FROM T_STUDENT WHERE GRADE =4;
SELECT NAME 이름, GRADE 학년, WEIGHT 몸무게
FROM T_STUDENT 
WHERE WEIGHT <ALL (SELECT WEIGHT FROM T_STUDENT WHERE GRADE =4)













