SELECT * FROM TEST_MEMBER ;

INSERT INTO TEST_MEMBER VALUES(10, '남윤주', SYSDATE);
SELECT * FROM TEST_MEMBER ;

INSERT INTO TEST_MEMBER VALUES(22, '이승환', '1994-02-21');
INSERT INTO TEST_MEMBER VALUES(17, '윤종섭', '2019-08-03');
INSERT INTO TEST_MEMBER VALUES('', '이예지', ''); -- 비어있는 '' 문자열을 INSERT 하면 NULL 값으로 처리한다. 
--INSERT INTO TEST_MEMBER VALUES(10, '', SYSDATE); --  cannot insert NULL
INSERT INTO TEST_MEMBER VALUES(NULL, '문상현', '2017-01-01');

-- dBeaver 에서는 기본적으로 auto-COMMIT 수행 